name: doclense
description: An Indian made Open source PDF creator Android app
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  camera: ^0.11.3
  double_back_to_close_app: ^2.1.0
  easy_folder_picker: ^1.3.4
  flutter_launcher_icons: ^0.14.4
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.2
  fluttertoast: ^9.0.0
  # gallery_saver: 
  image_gallery_saver_plus: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  image: ^4.5.4
  image_cropper: ^11.0.0
  image_picker: 
  intl: 
  introduction_screen: ^4.0.0
  open_file: ^3.5.10
  package_info_plus: 8.3.1
  path:  ^1.9.1
  path_provider: ^2.1.5
  pdf: 
  permission_handler: 
  photofilters:
   path:  /home/jinosh/Program/open_source/photofilters
    # git: https://github.com/jinosh05/photofilters
  printing: ^5.14.2
  provider: ^6.1.5+1
  quick_actions: ^1.1.0
  rating_dialog: ^2.0.4
  # share: ^2.0.4
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  source_span: ^1.10.1
  url_launcher: ^6.3.2
  wiredash: ^2.6.0
  device_info_plus: ^12.2.0

dev_dependencies:
  build_runner: ^2.4.8
  # flutter_test:
  #   sdk: flutter
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.3.10
  lint: ^2.1.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/app_icon.png
  branding: assets/doclense.png
  color_dark: "000000"
  image_dark: assets/app_icon.png
  branding_dark: assets/doclense.png

  android_12:
    image: assets/app_icon.png
    icon_background_color: "#ffffff"
    image_dark: assets/app_icon.png
    icon_background_color_dark: "#000000"

  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/aboutPage/
    - assets/images/team/
